# Generate Report
- name: Generate Report
  run: |
    newman run "TestCollection.postman_collection9.json" -e "MasterAPI ENV.postman_environment1.json" -r htmlextra --reporter-htmlextra-export $(Build.ArtifactStagingDirectory)/report.html

# Publish the Report
- name: Publish Report
  uses: actions/upload-artifact@v2
  with:
    name: Reports
    path: $(Build.ArtifactStagingDirectory)/report.html
